version: "3.5"

name: sam-store-homolog

volumes: 
  sam-store-homolog-volume:
    external: true

services: 
  samstore-mysql:
    image: mysql:8.0
    container_name: samstore-mysql-homolog
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ZaAbVs6CTmgia0QXxe
    volumes:
      - sam-store-homolog-volume:/var/lib/mysql


  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: samstore-rabbitmq-homolog
    environment:  
      RABBITMQ_DEFAULT_USER: "samstore"
      RABBITMQ_DEFAULT_PASS: "samstore"
    ports:
      - 5672:5672
      - 15672:15672


  catalog-api: 
    image: bit-buddies/samstore-catalog-api-homolog:latest
    container_name: samstore-catalog-api-homolog
    build: 
      context: ../src
      dockerfile: Services/Store/Catalog/SamStore.Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - ASPNETCORE_URLS=http://*:5229
    ports:
      - 5229:5229
    depends_on: 
      - rabbitmq
      - samstore-mysql


  authentication-api: 
    image: bit-buddies/samstore-authentication-api-homolog:latest
    container_name: samstore-authentication-api-homolog
    build: 
      context: ../src
      dockerfile: Services/Store/Authentication/SamStore.Authentication.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - ASPNETCORE_URLS=http://*:5274
    ports:
      - 5274:5274
    depends_on: 
      - rabbitmq
      - samstore-mysql


  client-web: 
    image: bit-buddies/sam-store-web-homolog:latest
    container_name: samstore-web-homolog
    build:
      context: ../src/Clients/Web/SamStoreWeb/
      dockerfile: Dockerfile
    ports:
      - 4201:4200
    command: "ng serve --host 0.0.0.0 --configuration=homolog --port 4200 --disable-host-check"
    depends_on: 
      - catalog-api
