// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamStore.Catalogo.API.Data.Contexts;

#nullable disable

namespace SamStore.Catalogo.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20230128163227_Catalog_Version_2.0")]
    partial class Catalog_Version_20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SamStore.Catalogo.API.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AlteredAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("altered_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<bool>("Removed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("removed");

                    b.Property<decimal>("Value")
                        .HasColumnType("DECIMAL(65,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8433b7da-f9a3-4528-9ca0-34c114a835c8"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Omêga",
                            Quantity = 0,
                            Removed = false,
                            Value = 259.99m
                        },
                        new
                        {
                            Id = new Guid("d56f3525-27ef-40af-a234-50e5703acee1"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Scarlatte",
                            Quantity = 0,
                            Removed = false,
                            Value = 629.99m
                        },
                        new
                        {
                            Id = new Guid("a30f2b54-c049-4736-9823-120ca90f557f"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Fiarrut",
                            Quantity = 0,
                            Removed = false,
                            Value = 349.99m
                        },
                        new
                        {
                            Id = new Guid("370e46af-9e46-4691-8482-788a10ca6e1d"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Gonjour Lamari",
                            Quantity = 0,
                            Removed = false,
                            Value = 559.99m
                        },
                        new
                        {
                            Id = new Guid("8fc34042-dc07-4afa-a0fb-db5b44abc556"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Vilé Toustã",
                            Quantity = 0,
                            Removed = false,
                            Value = 229.99m
                        },
                        new
                        {
                            Id = new Guid("4c8419c0-17fa-4f88-9b41-e74d4a1d1e67"),
                            AlteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Descrição",
                            Image = "",
                            Name = "Frankfourd Stoitelle",
                            Quantity = 0,
                            Removed = false,
                            Value = 129.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
